package com.crossge.necessities.Economy;

import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.util.Arrays;
import java.util.Collections;

public class MaterialNames {
    private final File configFileNames = new File("plugins/Necessities/Economy", "itemnames.yml");
    private final File configFileFriendlyNames = new File("plugins/Necessities/Economy", "friendlynames.yml");
    private final File configFilePluralNames = new File("plugins/Necessities/Economy", "pluralnames.yml");

    public void setIds() {//TODO: ability to set for damage values the names of different items
        setNames();
        setFriendlyNames();
        setPluralNames();
    }

    private void setNames() {
        YamlConfiguration configNames = YamlConfiguration.loadConfiguration(configFileNames);
        configNames.set("GRASS", Collections.singletonList("GRASSBLOCK"));
        configNames.set("COBBLESTONE", Collections.singletonList("COBBLE"));
        configNames.set("WOOD", Collections.singletonList("PLANK"));
        configNames.set("WATER", Collections.singletonList("WATERSOURCE"));
        configNames.set("STATIONARY_WATER", Arrays.asList("STILLWATER", "WATERSTILL"));
        configNames.set("LAVA", Collections.singletonList("LAVASOURCE"));
        configNames.set("STATIONARY_LAVA", Arrays.asList("STILLLAVA", "LAVASTILL"));
        configNames.set("LOG", Collections.singletonList("BARK"));
        configNames.set("LAPIS_ORE", Collections.singletonList("LAPISLAZULIORE"));
        configNames.set("LAPIS_BLOCK", Collections.singletonList("LAPISLAZULIBLOCK"));
        configNames.set("PISTON_STICKY_BASE", Collections.singletonList("STICKYPISTON"));
        configNames.set("WEB", Arrays.asList("COBWEB", "SPIDERWEB"));
        configNames.set("PISTON_BASE", Collections.singletonList("PISTON"));
        configNames.set("YELLOW_FLOWER", Collections.singletonList("DANDELION"));
        configNames.set("RED_ROSE", Arrays.asList("REDFLOWER", "POPPY", "ROSE", "FLOWER"));
        configNames.set("GOLD_BLOCK", Collections.singletonList("BLOCKOFGOLD"));
        configNames.set("IRON_BLOCK", Collections.singletonList("BLOCKOFIRON"));
        configNames.set("STEP", Collections.singletonList("SLAB"));
        configNames.set("BRICK", Collections.singletonList("BRICKS"));
        configNames.set("MOSSY_COBBLESTONE", Arrays.asList("MOSSYCOBBLE", "MOSSSTONE", "MOSSYSTONE", "MOSSCOBBLE", "MOSSCOBBLESTONE"));
        configNames.set("MOB_SPAWNER", Arrays.asList("SPAWNER", "MONSTERSPAWNER"));
        configNames.set("WOOD_STAIRS", Arrays.asList("OAKWOODSTAIR", "OAKWOODSTAIRS"));
        configNames.set("DIAMOND_BLOCK", Collections.singletonList("BLOCKOFDIAMOND"));
        configNames.set("WORKBENCH", Collections.singletonList("CRAFTINGTABLE"));
        configNames.set("SOIL", Arrays.asList("FARMLAND", "TILLEDSOIL", "TILLEDGROUND"));
        configNames.set("RAILS", Collections.singletonList("RAIL"));
        configNames.set("COBBLESTONE_STAIRS", Arrays.asList("COBBLESTAIRS", "STONESTAIRS"));
        configNames.set("STONE_PLATE", Arrays.asList("STONEPRESSUREPLATE", "PRESSUREPLATE"));
        configNames.set("WOOD_PLATE", Collections.singletonList("WOODPRESSUREPLATE"));
        configNames.set("REDSTONE_TORCH_ON", Collections.singletonList("REDSTONETORCH"));
        configNames.set("STONE_BUTTON", Collections.singletonList("BUTTON"));
        configNames.set("GLOWSTONE", Arrays.asList("GLOWSTONEBLOCK", "BLOCKOFGLOWSTONE"));
        configNames.set("STAINED_GLASS", Collections.singletonList("TINTEDGLASS"));
        configNames.set("MONSTER_EGGS", Collections.singletonList("MONSTEREGG"));
        configNames.set("SMOOTH_BRICK", Collections.singletonList("STONEBRICK"));
        configNames.set("IRON_FENCE", Arrays.asList("IRONBARS", "IRONBAR"));
        configNames.set("THIN_GLASS", Collections.singletonList("GLASSPANE"));
        configNames.set("VINE", Collections.singletonList("VINES"));
        configNames.set("SMOOTH_STAIRS", Collections.singletonList("STONEBRICKSTAIRS"));
        configNames.set("MYCEL", Collections.singletonList("MYCELIUM"));
        configNames.set("WATER_LILY", Arrays.asList("LILY", "LILYPAD"));
        configNames.set("NETHER_FENCE", Collections.singletonList("NETHERBRICKFENCE"));
        configNames.set("ENDER_PORTAL", Collections.singletonList("ENDPORTAL"));
        configNames.set("ENDER_PORTAL_FRAME", Collections.singletonList("ENDPORTALFRAME"));
        configNames.set("ENDER_STONE", Collections.singletonList("ENDSTONE"));
        configNames.set("REDSTONE_LAMP_OFF", Arrays.asList("LAMPOFF", "REDSTONELAMP", "LAMP"));
        configNames.set("WOOD_STEP", Collections.singletonList("WOODSLAB"));
        configNames.set("EMERALD_BLOCK", Collections.singletonList("BLOCKOFEMERALD"));
        configNames.set("SPRUCE_WOOD_STAIRS", Collections.singletonList("SPRUCESTAIRS"));
        configNames.set("BIRCH_WOOD_STAIRS", Collections.singletonList("BIRCHSTAIRS"));
        configNames.set("JUNGLE_WOOD_STAIRS", Collections.singletonList("JUNGLESTAIRS"));
        configNames.set("COMMAND", Collections.singletonList("COMMANDBLOCK"));
        configNames.set("COBBLE_WALL", Collections.singletonList("COBBLESTONEWALL"));
        configNames.set("TRAPPED_CHEST", Collections.singletonList("REDSTONECHEST"));
        configNames.set("GOLD_PLATE", Arrays.asList("GOLDPRESSUREPLATE", "LIGHTPRESSUREPLATE", "WEIGHTEDPRESSUREPLATELIGHT"));
        configNames.set("IRON_PLATE", Arrays.asList("IRONPRESSUREPLATE", "HEAVYPRESSUREPLATE", "WEIGHTEDPRESSUREPLATEHEAVY"));
        configNames.set("STAINED_GLASS_PANE", Collections.singletonList("STAINEDTHINGLASS"));
        configNames.set("LEAVES_2", Collections.singletonList("ACACIALEAVES"));
        configNames.set("LOG_2", Arrays.asList("ACACIALOG", "ACACIABARK"));
        configNames.set("HAY_BLOCK", Arrays.asList("HAY", "HAYBALE"));
        configNames.set("HARD_CLAY", Collections.singletonList("HARDENEDCLAY"));
        configNames.set("COAL_BLOCK", Collections.singletonList("BLOCKOFCOAL"));
        configNames.set("IRON_SPADE", Collections.singletonList("IRONSHOVEL"));
        configNames.set("IRON_PICKAXE", Collections.singletonList("IRONPICK"));
        configNames.set("WOOD_SWORD", Collections.singletonList("WOODENSWORD"));
        configNames.set("WOOD_SPADE", Arrays.asList("WOODSHOVEL", "WOODENSHOVEL"));
        configNames.set("WOOD_PICKAXE", Arrays.asList("WOODPICK", "WOODENPICKAXE", "WOODENPICK"));
        configNames.set("WOOD_AXE", Collections.singletonList("WOODENAXE"));
        configNames.set("STONE_SPADE", Collections.singletonList("STONESHOVEL"));
        configNames.set("STONE_PICKAXE", Collections.singletonList("STONEPICK"));
        configNames.set("DIAMOND_SPADE", Collections.singletonList("DIAMONDSHOVEL"));
        configNames.set("DIAMOND_PICKAXE", Collections.singletonList("DIAMONDPICK"));
        configNames.set("MUSHROOM_SOUP", Arrays.asList("SOUP", "MUSHROOMSTEW", "STEW"));
        configNames.set("GOLD_SWORD", Collections.singletonList("GOLDENSWORD"));
        configNames.set("GOLD_SPADE", Arrays.asList("GOLDSHOVEL", "GOLDENSHOVEL", "GOLDENSPADE"));
        configNames.set("GOLD_PICKAXE", Arrays.asList("GOLDPICK", "GOLDENPICKAXE", "GOLDENPICK"));
        configNames.set("GOLD_AXE", Collections.singletonList("GOLDENAXE"));
        configNames.set("SULPHUR", Collections.singletonList("GUNPOWDER"));
        configNames.set("WOOD_HOE", Collections.singletonList("WOODENHOE"));
        configNames.set("GOLD_HOE", Collections.singletonList("GOLDENHOE"));
        configNames.set("LEATHER_HELMET", Arrays.asList("LEATHERCAP", "LEATHERHAT"));
        configNames.set("LEATHER_CHESTPLATE", Arrays.asList("LEATHERTUNIC", "SHIRT", "LEATHERSHIRT"));
        configNames.set("LEATHER_LEGGINGS", Arrays.asList("LEATHERPANTS", "JEANS"));
        configNames.set("LEATHER_BOOTS", Collections.singletonList("LEATHERSHOES"));
        configNames.set("CHAINMAIL_HELMET", Arrays.asList("CHAINMAILHAT", "CHAINMAILCAP"));
        configNames.set("CHAINMAIL_CHESTPLATE", Collections.singletonList("CHAINMAILSHIRT"));
        configNames.set("CHAINMAIL_LEGGINGS", Collections.singletonList("CHAINMAILPANTS"));
        configNames.set("CHAINMAIL_BOOTS", Collections.singletonList("CHAINMAILSHOES"));
        configNames.set("IRON_HELMET", Arrays.asList("IRONHAT", "IRONCAP"));
        configNames.set("IRON_CHESTPLATE", Collections.singletonList("IRONSHIRT"));
        configNames.set("IRON_LEGGINGS", Collections.singletonList("IRONPANTS"));
        configNames.set("IRON_BOOTS", Collections.singletonList("IRONSHOES"));
        configNames.set("DIAMOND_HELMET", Arrays.asList("DIAMONDHAT", "DIAMONDCAP"));
        configNames.set("DIAMOND_CHESTPLATE", Collections.singletonList("DIAMONDSHIRT"));
        configNames.set("DIAMOND_LEGGINGS", Collections.singletonList("DIAMONDPANTS"));
        configNames.set("DIAMOND_BOOTS", Collections.singletonList("DIAMONDSHOES"));
        configNames.set("GOLD_HELMET", Arrays.asList("GOLDCAP", "GOLDHAT", "GOLDENHELMET", "GOLDENCAP", "GOLDENHAT"));
        configNames.set("GOLD_CHESTPLATE", Arrays.asList("GOLDSHIRT", "GOLDENSHIRT", "GOLDENCHESTPLATE"));
        configNames.set("GOLD_LEGGINGS", Arrays.asList("GOLDPANTS", "GOLDENPANTS", "GOLDENLEGGINGS"));
        configNames.set("GOLD_BOOTS", Arrays.asList("GOLDSHOES", "GOLDENSHOES", "GOLDENBOOTS"));
        configNames.set("PORK", Arrays.asList("RAWPORK", "RAWPORKCHOP", "PORKCHOP"));
        configNames.set("GRILLED_PORK", Arrays.asList("GRILLEDPORKCHOP", "COOKEDPORK", "COOKEDPORKCHOP"));
        configNames.set("GOLDEN_APPLE", Arrays.asList("GOLDAPPLE", "GODAPPLE"));
        configNames.set("WOOD_DOOR", Arrays.asList("DOOR", "WOODENDOOR"));
        configNames.set("REDSTONE", Arrays.asList("REDSTONEDUST", "WIRE", "REDSTONEWIRE"));
        configNames.set("MILK_BUCKET", Collections.singletonList("MILK"));
        configNames.set("CLAY_BRICK", Collections.singletonList("BRICK"));
        configNames.set("SUGAR_CANE", Arrays.asList("REED", "REEDS", "SUGARCANES"));
        configNames.set("STORAGE_MINECART", Collections.singletonList("MINECARTWITHCHEST"));
        configNames.set("POWERED_MINECART", Collections.singletonList("MINECARTWITHFURNACE"));
        configNames.set("WATCH", Collections.singletonList("CLOCK"));
        configNames.set("COOKED_FISH", Collections.singletonList("BAKEDFISH"));
        configNames.set("RAW_FISH", Collections.singletonList("FISH"));
        configNames.set("INK_SACK", Arrays.asList("INK", "DYE"));
        configNames.set("DIODE", Arrays.asList("REPEATER", "REDSTONEREPEATER"));
        configNames.set("RAW_BEEF", Collections.singletonList("RAWSTEAK"));
        configNames.set("COOKED_BEEF", Arrays.asList("STEAK", "COOKEDSTEAK", "BEEF"));
        configNames.set("COOKED_CHICKEN", Collections.singletonList("CHICKEN"));
        configNames.set("ROTTEN_FLESH", Arrays.asList("ZOMBIEFLESH", "ZOMBIEBRAIN"));
        configNames.set("NETHER_STALK", Collections.singletonList("NETHERWART"));
        configNames.set("GLASS_BOTTLE", Collections.singletonList("BOTTLE"));
        configNames.set("BREWING_STAND_ITEM", Collections.singletonList("BREWINGSTAND"));
        configNames.set("CAULDRON_ITEM", Collections.singletonList("CAULDRON"));
        configNames.set("EYE_OF_ENDER", Collections.singletonList("ENDEREYE"));
        configNames.set("SPECKLED_MELON", Collections.singletonList("GLISTERINGMELON"));
        configNames.set("EXP_BOTTLE", Arrays.asList("BOTTLEOENCHANTING", "XPBOTTLE", "EXP", "XP", "BOTTLEDXP", "BOTTLEDEXP"));
        configNames.set("FIREBALL", Collections.singletonList("FIRECHARGE"));
        configNames.set("BOOK_AND_QUILL", Collections.singletonList("UNPUBLISHEDBOOK"));
        configNames.set("WRITTEN_BOOK", Collections.singletonList("PUBLISHEDBOOK"));
        configNames.set("FLOWER_POT_ITEM", Collections.singletonList("FLOWERPOT"));
        configNames.set("CARROT_ITEM", Collections.singletonList("CARROT"));
        configNames.set("POTATO_ITEM", Collections.singletonList("POTATO"));
        configNames.set("BAKED_POTATO", Collections.singletonList("COOKEDPOTATO"));
        configNames.set("GOLDEN_CARROT", Collections.singletonList("GOLDCARROT"));
        configNames.set("EMPTY_MAP", Collections.singletonList("MAP"));
        configNames.set("SKULL_ITEM", Arrays.asList("HEAD", "SKULL"));
        configNames.set("CARROT_STICK", Collections.singletonList("CARROTONASTICK"));
        configNames.set("NETHER_STAR", Arrays.asList("WITHERSTAR", "STAR"));
        configNames.set("PUMPKIN_PIE", Collections.singletonList("PIE"));
        configNames.set("FIREWORK", Collections.singletonList("FIREWORKROCKET"));
        configNames.set("FIREWORK_CHARGE", Collections.singletonList("FIREWORKSTAR"));
        configNames.set("REDSTONE_COMPARATOR", Collections.singletonList("COMPARATOR"));
        configNames.set("QUARTZ", Collections.singletonList("NETHERQUARTZ"));
        configNames.set("EXPLOSIVE_MINECART", Arrays.asList("MINECARTWITHTNT", "TNTMINECART"));
        configNames.set("HOPPER_MINECART", Collections.singletonList("MINECARTWITHHOPPER"));
        configNames.set("IRON_BARDING", Arrays.asList("IRONHORSEARMOR", "IRONARMOR"));
        configNames.set("GOLD_BARDING", Arrays.asList("GOLDHORSEARMOR", "GOLDARMOR"));
        configNames.set("DIAMOND_BARDING", Arrays.asList("DIAMONDHORSEARMOR", "DIAMONDARMOR"));
        configNames.set("LEASH", Collections.singletonList("LEAD"));
        configNames.set("COMMAND_MINECART", Arrays.asList("COMMANDBLOCKMINECART", "MINECARTWITHCOMMANDBLOCK", "COMMANDINMINECART", "MINECARTWITHCOMMAND"));
        configNames.set("GOLD_RECORD", Arrays.asList("13", "MUSICDISC13", "MUSIC13", "C41813"));
        configNames.set("GREEN_RECORD", Arrays.asList("CAT", "MUSICDISCCAT", "MUSICCAT", "C418CAT"));
        configNames.set("RECORD_3", Arrays.asList("BLOCKS", "MUSICDISCBLOCKS", "MUSICBLOCKS", "C418BLOCKS"));
        configNames.set("RECORD_4", Arrays.asList("CHIRP", "MUSICDISCCHIRP", "MUSICCHIRP", "C418CHIRP"));
        configNames.set("RECORD_5", Arrays.asList("FAR", "MUSICDISCFAR", "MUSICFAR", "C418FAR"));
        configNames.set("RECORD_6", Arrays.asList("MALL", "MUSICDISCMALL", "MUSICMALL", "C418MALL"));
        configNames.set("RECORD_7", Arrays.asList("MELLOHI", "MUSICDISCMELLOHI", "MUSICMELLOHI", "C418MELLOHI"));
        configNames.set("RECORD_8", Arrays.asList("STAL", "MUSICDISCSTAL", "MUSICSTAL", "C418STAL"));
        configNames.set("RECORD_9", Arrays.asList("STRAD", "MUSICDISCSTRAD", "MUSICSTRAD", "C418STRAD"));
        configNames.set("RECORD_10", Arrays.asList("WARD", "MUSICDISCWARD", "MUSICWARD", "C418WARD"));
        configNames.set("RECORD_11", Arrays.asList("11", "MUSICDISC11", "MUSIC11", "C41811"));
        configNames.set("RECORD_12", Arrays.asList("WAIT", "MUSICDISCWAIT", "MUSICWAIT", "C418WAIT"));
        configNames.set("STONE_SLAB2", Collections.singletonList("REDSANDSTONESLAB"));
        configNames.set("END_BRICKS", Arrays.asList("ENDSTONEBRICKS", "ENDERSTONEBRICKS"));
        configNames.set("CHORUS_FRUIT_POPPED", Collections.singletonList("POPPEDCHORUSFRUIT"));
        configNames.set("ELYTRA", Collections.singletonList("WING"));
        configNames.set("END_CRYSTAL", Collections.singletonList("ENDERCRYSTAL"));
        configNames.set("COMMAND_REPEATING", Arrays.asList("REPEATINGCOMMANDBLOCK", "COMMANDBLOCKREPEATING", "REPEATINGCOMMAND"));
        configNames.set("COMMAND_CHAIN", Arrays.asList("CHAINCOMMANDBLOCK", "CHAINCOMMAND", "COMMANDBLOCKCHAIN"));
        configNames.set("MAGMA", Collections.singletonList("MAGMABLOCK"));
        configNames.set("TOTEM", Collections.singletonList("UNDYINGTOTEM"));
        try {
            configNames.save(configFileNames);
        } catch (Exception ignored) {
        }
    }

    private void setFriendlyNames() {
        YamlConfiguration configFriendlyNames = YamlConfiguration.loadConfiguration(configFileFriendlyNames);
        configFriendlyNames.set("COBBLESTONE", "COBBLE");
        configFriendlyNames.set("WOOD", "PLANK");
        configFriendlyNames.set("LAPIS_ORE", "LAPIS LAZULI ORE");
        configFriendlyNames.set("LAPIS_BLOCK", "LAPIS LAZULI BLOCK");
        configFriendlyNames.set("PISTON_STICKY_BASE", "STICKY PISTON");
        configFriendlyNames.set("WEB", "COBWEB");
        configFriendlyNames.set("PISTON_BASE", "PISTON");
        configFriendlyNames.set("YELLOW_FLOWER", "DANDELION");
        configFriendlyNames.set("RED_ROSE", "FLOWER");
        configFriendlyNames.set("GOLD_BLOCK", "BLOCK OF GOLD");
        configFriendlyNames.set("IRON_BLOCK", "BLOCK OF IRON");
        configFriendlyNames.set("STEP", "SLAB");
        configFriendlyNames.set("BRICK", "BRICKS");
        configFriendlyNames.set("MOB_SPAWNER", "MONSTER SPAWNER");
        configFriendlyNames.set("DIAMOND_BLOCK", "BLOCK OF DIAMOND");
        configFriendlyNames.set("WORKBENCH", "CRAFTING TABLE");
        configFriendlyNames.set("SOIL", "FARMLAND");
        configFriendlyNames.set("COBBLESTONE_STAIRS", "STONE STAIR");
        configFriendlyNames.set("STONE_PLATE", "PRESSURE PLATE");
        configFriendlyNames.set("WOOD_PLATE", "PRESSURE PLATE");
        configFriendlyNames.set("REDSTONE_TORCH_ON", "REDSTONE TORCH");
        configFriendlyNames.set("STONE_BUTTON", "BUTTON");
        configFriendlyNames.set("GLOWSTONE", "BLOCK OF GLOWSTONE");
        configFriendlyNames.set("MONSTER_EGGS", "MONSTER EGG");
        configFriendlyNames.set("SMOOTH_BRICK", "STONE BRICK");
        configFriendlyNames.set("IRON_FENCE", "IRON BAR");
        configFriendlyNames.set("THIN_GLASS", "GLASS PANE");
        configFriendlyNames.set("VINE", "VINES");
        configFriendlyNames.set("SMOOTH_STAIRS", "STONE BRICK STAIRS");
        configFriendlyNames.set("MYCEL", "MYCELIUM");
        configFriendlyNames.set("WATER_LILY", "LILYPAD");
        configFriendlyNames.set("NETHER_FENCE", "NETHER BRICK FENCE");
        configFriendlyNames.set("ENDER_PORTAL", "END PORTAL");
        configFriendlyNames.set("ENDER_PORTAL_FRAME", "END PORTAL FRAME");
        configFriendlyNames.set("ENDER_STONE", "END STONE");
        configFriendlyNames.set("REDSTONE_LAMP_OFF", "REDSTONE LAMP");
        configFriendlyNames.set("WOOD_STEP", "WOOD SLAB");
        configFriendlyNames.set("EMERALD_BLOCK", "BLOCK OF EMERALD");
        configFriendlyNames.set("SPRUCE_WOOD_STAIRS", "SPRUCE STAIR");
        configFriendlyNames.set("BIRCH_WOOD_STAIRS", "BIRCH STAIR");
        configFriendlyNames.set("JUNGLE_WOOD_STAIRS", "JUNGLE STAIR");
        configFriendlyNames.set("COMMAND", "COMMAND BLOCK");
        configFriendlyNames.set("COBBLE_WALL", "COBBLESTONE WALL");
        configFriendlyNames.set("GOLD_PLATE", "WEIGHTED PRESSURE PLATE LIGHT");
        configFriendlyNames.set("IRON_PLATE", "WEIGHTED PRESSURE PLATE HEAVY");
        configFriendlyNames.set("LEAVES_2", "ACACIA LEAVES");
        configFriendlyNames.set("LOG_2", "ACACIA LOG");
        configFriendlyNames.set("HAY_BLOCK", "HAY BALE");
        configFriendlyNames.set("HARD_CLAY", "HARDENED CLAY");
        configFriendlyNames.set("COAL_BLOCK", "BLOCK OF COAL");
        configFriendlyNames.set("IRON_SPADE", "IRON SHOVEL");
        configFriendlyNames.set("WOOD_SWORD", "WOODEN SWORD");
        configFriendlyNames.set("WOOD_SPADE", "WOODEN SHOVEL");
        configFriendlyNames.set("WOOD_PICKAXE", "WOODEN PICKAXE");
        configFriendlyNames.set("WOOD_AXE", "WOODEN AXE");
        configFriendlyNames.set("STONE_SPADE", "STONE SHOVEL");
        configFriendlyNames.set("DIAMOND_SPADE", "DIAMOND SHOVEL");
        configFriendlyNames.set("MUSHROOM_SOUP", "MUSHROOM STEW");
        configFriendlyNames.set("GOLD_SWORD", "GOLDEN SWORD");
        configFriendlyNames.set("GOLD_SPADE", "GOLDEN SHOVEL");
        configFriendlyNames.set("GOLD_PICKAXE", "GOLDEN PICKAXE");
        configFriendlyNames.set("GOLD_AXE", "GOLDEN AXE");
        configFriendlyNames.set("SULPHUR", "GUNPOWDER");
        configFriendlyNames.set("WOOD_HOE", "WOODEN HOE");
        configFriendlyNames.set("GOLD_HOE", "GOLDEN HOE");
        configFriendlyNames.set("LEATHER_HELMET", "LEATHER CAP");
        configFriendlyNames.set("LEATHER_CHESTPLATE", "LEATHER TUNIC");
        configFriendlyNames.set("LEATHER_LEGGINGS", "LEATHER PANT");
        configFriendlyNames.set("LEATHER_BOOTS", "LEATHER BOOT");
        configFriendlyNames.set("GOLD_HELMET", "GOLDEN HELMET");
        configFriendlyNames.set("GOLD_CHESTPLATE", "GOLDEN CHESTPLATE");
        configFriendlyNames.set("GOLD_LEGGINGS", "GOLDEN LEGGING");
        configFriendlyNames.set("GOLD_BOOTS", "GOLDEN BOOT");
        configFriendlyNames.set("IRON_LEGGINGS", "IRON LEGGING");
        configFriendlyNames.set("IRON_BOOTS", "IRON BOOT");
        configFriendlyNames.set("DIAMOND_LEGGINGS", "DIAMOND LEGGING");
        configFriendlyNames.set("DIAMOND_BOOTS", "DIAMOND BOOT");
        configFriendlyNames.set("CHAINMAIL_LEGGINGS", "CHAINMAIL LEGGING");
        configFriendlyNames.set("CHAINMAIL_BOOTS", "CHAINMAIL BOOT");
        configFriendlyNames.set("PORK", "RAW PORKCHOP");
        configFriendlyNames.set("GRILLED_PORK", "COOKED PORKCHOP");
        configFriendlyNames.set("WOOD_DOOR", "WOODEN DOOR");
        configFriendlyNames.set("MILK_BUCKET", "MILK");
        configFriendlyNames.set("CLAY_BRICK", "BRICK");
        configFriendlyNames.set("STORAGE_MINECART", "MINECART WITH CHEST");
        configFriendlyNames.set("POWERED_MINECART", "MINECART WITH FURNACE");
        configFriendlyNames.set("WATCH", "CLOCK");
        configFriendlyNames.set("INK_SACK", "DYE");
        configFriendlyNames.set("DIODE", "REDSTONE REPEATER");
        configFriendlyNames.set("COOKED_BEEF", "STEAK");
        configFriendlyNames.set("NETHER_STALK", "NETHER WART");
        configFriendlyNames.set("BREWING_STAND_ITEM", "BREWING STAND");
        configFriendlyNames.set("CAULDRON_ITEM", "CAULDRON");
        configFriendlyNames.set("FLOWER_POT_ITEM", "FLOWER POT");
        configFriendlyNames.set("CARROT_ITEM", "CARROT");
        configFriendlyNames.set("POTATO_ITEM", "POTATO");
        configFriendlyNames.set("SPECKLED_MELON", "GLISTERING MELON");
        configFriendlyNames.set("EXP_BOTTLE", "BOTTLE O ENCHANTING");
        configFriendlyNames.set("FIREBALL", "FIRE CHARGE");
        configFriendlyNames.set("SKULL_ITEM", "SKULL");
        configFriendlyNames.set("CARROT_STICK", "CARROT ON A STICK");
        configFriendlyNames.set("FIREWORK", "FIREWORK ROCKET");
        configFriendlyNames.set("FIREWORK_CHARGE", "FIREWORK STAR");
        configFriendlyNames.set("QUARTZ", "NETHER QUARTZ");
        configFriendlyNames.set("EXPLOSIVE_MINECART", "MINECART WITH TNT");
        configFriendlyNames.set("HOPPER_MINECART", "MINECART WITH HOPPER");
        configFriendlyNames.set("IRON_BARDING", "IRON HORSE ARMOR");
        configFriendlyNames.set("GOLD_BARDING", "GOLD HORSE ARMOR");
        configFriendlyNames.set("DIAMOND_BARDING", "DIAMOND HORSE ARMOR");
        configFriendlyNames.set("LEASH", "LEAD");
        configFriendlyNames.set("COMMAND_MINECART", "MINECART WITH COMMAND BLOCK");
        configFriendlyNames.set("GOLD_RECORD", "C418 - 13");
        configFriendlyNames.set("GREEN_RECORD", "C418 - CAT");
        configFriendlyNames.set("RECORD_3", "C418 - BLOCKS");
        configFriendlyNames.set("RECORD_4", "C418 - CHIRP");
        configFriendlyNames.set("RECORD_5", "C418 - FAR");
        configFriendlyNames.set("RECORD_6", "C418 - MALL");
        configFriendlyNames.set("RECORD_7", "C418 - MELLOHI");
        configFriendlyNames.set("RECORD_8", "C418 - STAL");
        configFriendlyNames.set("RECORD_9", "C418 - STRAD");
        configFriendlyNames.set("RECORD_10", "C418 - WARD");
        configFriendlyNames.set("RECORD_11", "C418 - 11");
        configFriendlyNames.set("RECORD_12", "C418 - WAIT");
        configFriendlyNames.set("WOOD_STAIRS", "WOOD STAIR");
        configFriendlyNames.set("RAILS", "RAIL");
        configFriendlyNames.set("COBBLESTONE_STAIRS", "COBBLESTONE STAIR");
        configFriendlyNames.set("BRICK_STAIRS", "BRICK STAIR");
        configFriendlyNames.set("NETHER_BRICK_STAIRS", "NETHER BRICK STAIR");
        configFriendlyNames.set("SANDSTONE_STAIRS", "SANDSTONE STAIR");
        configFriendlyNames.set("QUARTZ_STAIRS", "QUARTZ STAIR");
        configFriendlyNames.set("WOOD_BUTTON", "BUTTON");
        configFriendlyNames.set("DARK_OAK_STAIRS", "DARK OAK STAIR");
        configFriendlyNames.set("ACACIA_STAIRS", "ACACIA STAIR");
        configFriendlyNames.set("MELON_SEEDS", "MELON SEED");
        configFriendlyNames.set("PUMPKIN_SEEDS", "PUMPKIN SEED");
        configFriendlyNames.set("SHEARS", "SHEAR");
        configFriendlyNames.set("SEEDS", "SEED");
        configFriendlyNames.set("STONE_SLAB2", "RED SANDSTONE SLAB");
        configFriendlyNames.set("RED_SANDSTONE_STAIRS", "RED SANDSTONE STAIR");
        configFriendlyNames.set("END_BRICKS", "END STONE BRICK");
        configFriendlyNames.set("CHORUS_FRUIT_POPPED", "POPPED CHORUS FRUIT");
        configFriendlyNames.set("COMMAND_REPEATING", "REPEATING COMMAND BLOCK");
        configFriendlyNames.set("COMMAND_CHAIN", "CHAIN COMMAND BLOCK");
        configFriendlyNames.set("BEETROOT_SEEDS", "BEETROOT SEED");
        configFriendlyNames.set("PURPUR_STAIRS", "PURPUR STAIR");
        configFriendlyNames.set("MAGMA", "MAGMA BLOCK");
        configFriendlyNames.set("NETHER_WART_BLOCK", "NETHER WART BLOCK");
        configFriendlyNames.set("RED_NETHER_BRICK", "RED NETHER BRICK");
        configFriendlyNames.set("BONE_BLOCK", "BONE BLOCK");
        configFriendlyNames.set("STRUCTURE_VOID", "STRUCTURE VOID");
        configFriendlyNames.set("STRUCTURE_BLOCK", "STRUCTURE BLOCK");
        configFriendlyNames.set("SHULKER_SHELL", "SHULKER SHELL");
        configFriendlyNames.set("TOTEM", "TOTEM OF UNDYING");
        configFriendlyNames.set("SILVER_SHULKER_BOX", "LIGHT GRAY SHULKER BOX");
        try {
            configFriendlyNames.save(configFileFriendlyNames);
        } catch (Exception ignored) {
        }
    }

    private void setPluralNames() {
        YamlConfiguration configPluralNames = YamlConfiguration.loadConfiguration(configFilePluralNames);
        configPluralNames.set("PLANK", "PLANKS");
        configPluralNames.set("SAPPLING", "SAPPLINGS");
        configPluralNames.set("WOOD", "LOGS");
        configPluralNames.set("LAPISBLOCK", "LAPIS BLOCKS");
        configPluralNames.set("DISPENSER", "DISPENSERS");
        configPluralNames.set("NOTEBLOCK", "NOTE BLOCKS");
        configPluralNames.set("POWEREDRAIL", "POWERED RAILS");
        configPluralNames.set("DETECTORRAIL", "DETECTOR RAILS");
        configPluralNames.set("STICKYPISTON", "STICKY PISTONS");
        configPluralNames.set("COBWEB", "COBWEBS");
        configPluralNames.set("PISTON", "PISTONS");
        configPluralNames.set("DANDELION", "DANDELIONS");
        configPluralNames.set("FLOWER", "FLOWERS");
        configPluralNames.set("BROWNMUSHROOM", "BROWN MUSHROOMS");
        configPluralNames.set("REDMUSHROOM", "RED MUSHROOMS");
        configPluralNames.set("BLOCKOFGOLD", "BLOCKS OF GOLD");
        configPluralNames.set("BLOCKOFIRON", "BLOCKS OF IRON");
        configPluralNames.set("SLAB", "SLABS");
        configPluralNames.set("BOOKSHELF", "BOOKSHELVES");
        configPluralNames.set("TORCH", "TORCHES");
        configPluralNames.set("WOODSTAIR", "WOOD STAIRS");
        configPluralNames.set("CHEST", "CHESTS");
        configPluralNames.set("BLOCKOFDIAMOND", "BLOCKS OF DIAMOND");
        configPluralNames.set("CRAFTINGTABLE", "CRAFTING TABLES");
        configPluralNames.set("FURNACE", "FURNACES");
        configPluralNames.set("LADDER", "LADDERS");
        configPluralNames.set("RAIL", "RAILS");
        configPluralNames.set("STONESTAIR", "STONE STAIRS");
        configPluralNames.set("LEVER", "LEVERS");
        configPluralNames.set("PRESSUREPLATE", "PRESSURE PLATES");
        configPluralNames.set("REDSTONETORCH", "REDSTONE TORCHES");
        configPluralNames.set("BUTTON", "BUTTONS");
        configPluralNames.set("CACTUS", "CACTI");
        configPluralNames.set("JUKEBOX", "JUKEBOXES");
        configPluralNames.set("FENCE", "FENCES");
        configPluralNames.set("PUMPKIN", "PUMPKINS");
        configPluralNames.set("JACKOLANTERN", "JACK O LANTERNS");
        configPluralNames.set("TRAPDOOR", "TRAPDOORS");
        configPluralNames.set("STONEBRICK", "STONE BRICKS");
        configPluralNames.set("IRONBAR", "IRON BARS");
        configPluralNames.set("VINE", "VINES");
        configPluralNames.set("FENCEGATE", "FENCE GATES");
        configPluralNames.set("BRICKSTAIR", "BRICK STAIRS");
        configPluralNames.set("STONEBRICKSTAIR", "STONE BRICK STAIRS");
        configPluralNames.set("LILYPAD", "LILY PADS");
        configPluralNames.set("NETHERBRICK", "NETHER BRICKS");
        configPluralNames.set("NETHERBRICKFENCE", "NETHER BRICK FENCES");
        configPluralNames.set("NETHERBRICKSTAIR", "NETHER BRICK STAIRS");
        configPluralNames.set("ENCHANTMENTTABLE", "ENCHANTMENT TABLES");
        configPluralNames.set("REDSTONELAMP", "REDSTONE LAMPS");
        configPluralNames.set("WOODSSLAB", "WOOD SLABS");
        configPluralNames.set("SANDSTONESTAIR", "SANDSTONE STAIRS");
        configPluralNames.set("ENDERCHEST", "ENDER CHESTS");
        configPluralNames.set("TRIPWIREHOOK", "TRIP WIRE HOOKS");
        configPluralNames.set("BLOCKOFEMERALD", "BLOCKS OF EMERALD");
        configPluralNames.set("SPRUCESTAIR", "SPRUCE STAIRS");
        configPluralNames.set("BIRCHSTAIR", "BIRCH STAIRS");
        configPluralNames.set("JUNGLESTAIR", "JUNGLE STAIRS");
        configPluralNames.set("COBBLESTONEWALL", "COBBLESTONE WALLS");
        configPluralNames.set("ANVIL", "ANVILS");
        configPluralNames.set("TRAPPEDCHEST", "TRAPPED CHESTS");
        configPluralNames.set("WEIGHTEDPRESSUREPLATELIGHT", "WEIGHTED PRESSURE PLATES LIGHT");
        configPluralNames.set("WEIGHTEDPRESSUREPLATEHEAVY", "WEIGHTED PRESSURE PLATES HEAVY");
        configPluralNames.set("DAYLIGHTDETECTOR", "DAYLIGHT DETECTORS");
        configPluralNames.set("BLOCKOFREDSTONE", "BLOCKS OF REDSTONE");
        configPluralNames.set("HOPPER", "HOPPERS");
        configPluralNames.set("QUARTZBLOCK", "QUARTZ BLOCKS");
        configPluralNames.set("QUARTZSTAIR", "QUARTZ STAIRS");
        configPluralNames.set("ACTIVATORRAIL", "ACTIVATOR RAILS");
        configPluralNames.set("DROPPER", "DROPPERS");
        configPluralNames.set("ACACIALOG", "ACACIA LOGS");
        configPluralNames.set("ACACIASTAIR", "ACACIA STAIRS");
        configPluralNames.set("DARKOAKSTAIR", "DARK OAK STAIRS");
        configPluralNames.set("HAYBALE", "HAY BALES");
        configPluralNames.set("CARPET", "CARPETS");
        configPluralNames.set("BLOCKOFCOAL", "BLOCKS OF COAL");
        configPluralNames.set("IRONSHOVEL", "IRON SHOVELS");
        configPluralNames.set("IRONPICKAXE", "IRON PICKAXES");
        configPluralNames.set("IRONAXE", "IRON AXES");
        configPluralNames.set("APPLE", "APPLES");
        configPluralNames.set("BOW", "BOWS");
        configPluralNames.set("ARROW", "ARROWS");
        configPluralNames.set("DIAMOND", "DIAMONDS");
        configPluralNames.set("IRONINGOT", "IRON INGOTS");
        configPluralNames.set("GOLDINGOT", "GOLD INGOTS");
        configPluralNames.set("IRONSWORD", "IRON SWORDS");
        configPluralNames.set("WOODENSWORD", "WOODEN SWORDS");
        configPluralNames.set("WOODENSHOVEL", "WOODEN SHOVELS");
        configPluralNames.set("WOODENPICKAXE", "WOODEN PICKAXES");
        configPluralNames.set("WOODENAXE", "WOODEN AXES");
        configPluralNames.set("STONESWORD", "STONE SWORDS");
        configPluralNames.set("STONESHOVEL", "STONE SHOVELS");
        configPluralNames.set("STONEPICKAXE", "STONE PICKAXES");
        configPluralNames.set("STONEAXE", "STONE AXES");
        configPluralNames.set("DIAMONDSWORD", "DIAMOND SWORDS");
        configPluralNames.set("DIAMONDSHOVEL", "DIAMOND SHOVELS");
        configPluralNames.set("DIAMONDPICKAXE", "DIAMOND PICKAXES");
        configPluralNames.set("DIAMONDAXE", "DIAMOND AXES");
        configPluralNames.set("STICK", "STICKS");
        configPluralNames.set("BOWL", "BOWLS");
        configPluralNames.set("GOLDENSWORD", "GOLDEN SWORDS");
        configPluralNames.set("GOLDENSHOVEL", "GOLDEN SHOVELS");
        configPluralNames.set("GOLDENPICKAXE", "GOLDEN PICKAXES");
        configPluralNames.set("GOLDENAXE", "GOLDEN AXES");
        configPluralNames.set("FEATHER", "FEATHERS");
        configPluralNames.set("WOODENHOE", "WOODEN HOES");
        configPluralNames.set("STONEHOE", "STONE HOES");
        configPluralNames.set("IRONHOE", "IRON HOES");
        configPluralNames.set("DIAMONDHOE", "DIAMOND HOES");
        configPluralNames.set("GOLDENHOE", "GOLDEN HOUSE");
        configPluralNames.set("SEED", "SEEDS");
        configPluralNames.set("LEATHERCAP", "LEATHER CAPS");
        configPluralNames.set("LEATHERTUNIC", "LEATHER TUNICS");
        configPluralNames.set("LEATHERPANT", "LEATHER PANTS");
        configPluralNames.set("LEATHERBOOT", "LEATHER BOOTS");
        configPluralNames.set("CHAINMAILHELMET", "CHAINMAIL HELMETS");
        configPluralNames.set("CHAINMAILCHESTPLATE", "CHAINMAIL CHESTPLATES");
        configPluralNames.set("CHAINMAILLEGGING", "CHAINMAIL LEGGINGS");
        configPluralNames.set("CHAINMAILBOOT", "CHAINMAIL BOOTS");
        configPluralNames.set("IRONHELMET", "IRON HELMETS");
        configPluralNames.set("IRONCHESTPLATE", "IRON CHESTPLATES");
        configPluralNames.set("IRONLEGGING", "IRON LEGGINGS");
        configPluralNames.set("IRONBOOT", "IRON BOOTS");
        configPluralNames.set("DIAMONDHELMET", "DIAMOND HELMETS");
        configPluralNames.set("DIAMONDCHESTPLATE", "DIAMOND CHESTPLATES");
        configPluralNames.set("DIAMONDLEGGING", "DIAMOND LEGGINGS");
        configPluralNames.set("DIAMONDBOOT", "DIAMOND BOOTS");
        configPluralNames.set("GOLDENHELMET", "GOLDEN HELMETS");
        configPluralNames.set("GOLDENCHESTPLATE", "GOLDEN CHESTPLATES");
        configPluralNames.set("GOLDENLEGGING", "GOLDEN LEGGINGS");
        configPluralNames.set("GOLDENBOOT", "GOLDEN BOOTS");
        configPluralNames.set("RAWPORKCHOP", "RAW PORKCHOPS");
        configPluralNames.set("COOKEDPORKCHOP", "COOKED PORKCHOPS");
        configPluralNames.set("PAINTING", "PAINTINGS");
        configPluralNames.set("SIGN", "SIGNS");
        configPluralNames.set("WOODENDOOR", "WOODEN DOORS");
        configPluralNames.set("BUCKET", "BUCKETS");
        configPluralNames.set("WATERBUCKET", "WATER BUCKETS");
        configPluralNames.set("LAVABUCKET", "LAVA BUCKETS");
        configPluralNames.set("MINECART", "MINECARTS");
        configPluralNames.set("SADDLE", "SADDLES");
        configPluralNames.set("IRONDOOR", "IRON DOORS");
        configPluralNames.set("SNOWBALL", "SNOW BALLS");
        configPluralNames.set("BOAT", "BOATS");
        configPluralNames.set("MILKBUCKET", "MILK BUCKETS");
        configPluralNames.set("BRICK", "BRICKS");
        configPluralNames.set("CLAYBALL", "CLAY BALLS");
        configPluralNames.set("BOOK", "BOOKS");
        configPluralNames.set("SLIMEBALL", "SLIMEBALLS");
        configPluralNames.set("EGG", "EGGS");
        configPluralNames.set("COMPASS", "COMPASSES");
        configPluralNames.set("FISHINGROD", "");
        configPluralNames.set("CLOCK", "CLOCKS");
        configPluralNames.set("BONE", "BONES");
        configPluralNames.set("CAKE", "CAKES");
        configPluralNames.set("BED", "BEDS");
        configPluralNames.set("REDSTONEREPEATER", "REDSTONE REPEATERS");
        configPluralNames.set("COOKIE", "COOKIES");
        configPluralNames.set("SHEAR", "SHEARS");
        configPluralNames.set("MELON", "MELONS");
        configPluralNames.set("PUMPKINSEED", "PUMPKIN SEEDS");
        configPluralNames.set("MELONSEED", "MELON SEEDS");
        configPluralNames.set("STEAK", "STEAKS");
        configPluralNames.set("ENDERPEARL", "ENDER PEARLS");
        configPluralNames.set("BLAZEROD", "BLAZE RODS");
        configPluralNames.set("GHASTTEAR", "GHAST TEARS");
        configPluralNames.set("GOLDNUGGET", "GOLD NUGGETS");
        configPluralNames.set("NETHERWART", "NETHER WARTS");
        configPluralNames.set("GLASSBOTTLE", "GLASS BOTTLES");
        configPluralNames.set("SPIDEREYE", "SPIDER EYES");
        configPluralNames.set("FERMENTEDSPIDEREYE", "FERMENTED SPIDER EYES");
        configPluralNames.set("BREWINGSTAND", "BREWING STANDS");
        configPluralNames.set("CAULDRON", "CAULDRONS");
        configPluralNames.set("EYEOFENDER", "EYES OF ENDER");
        configPluralNames.set("GLISTERINGMELON", "GLISTERING MELONS");
        configPluralNames.set("BOTTLEOENCHANTING", "BOTTLES O ENCHANTING");
        configPluralNames.set("FIRECHARGE", "FIRE CHARGES");
        configPluralNames.set("EMERALD", "EMERALDS");
        configPluralNames.set("ITEMFRAME", "ITEM FRAMES");
        configPluralNames.set("FLOWERPOT", "FLOWER POTS");
        configPluralNames.set("CARROT", "CARROTS");
        configPluralNames.set("POTATO", "POTATOES");
        configPluralNames.set("BAKEDPOTATO", "BAKED POTATOES");
        configPluralNames.set("POISONOUSPOTATO", "POISONOUS POTATOES");
        configPluralNames.set("EMPTYMAP", "EMPTY MAPS");
        configPluralNames.set("GOLDENCARROT", "GOLDEN CARROTS");
        configPluralNames.set("PUMPKINPIE", "PUMPKIN PIES");
        configPluralNames.set("REDSTONECOMPARATOR", "REDSTONE COMPARATORS");
        configPluralNames.set("NETHERBRICKITEM", "NETHER BRICK ITEMS");
        configPluralNames.set("LEAD", "LEADS");
        configPluralNames.set("NAMETAG", "NAME TAGS");
        configPluralNames.set("SPONGE", "SPONGES");
        configPluralNames.set("SLIMEBLOCK", "SLIME BLOCKS");
        configPluralNames.set("REDSANDSTONESLAB", "RED SANDSTONE SLABS");
        configPluralNames.set("BARRIER", "BARRIERS");
        configPluralNames.set("IRONTRAPDOOR", "IRON TRAPDOORS");
        configPluralNames.set("SEALANTERN", "SEA LANTERNS");
        configPluralNames.set("REDSANDSTONESTAIR", "RED SANDSTONE STAIRS");
        configPluralNames.set("SPRUCEFENCEGATE", "SPRUCE FENCE GATES");
        configPluralNames.set("BIRCHFENCEGATE", "BIRCH FENCE GATES");
        configPluralNames.set("JUNGLEFENCEGATE", "JUNGLE FENCE GATES");
        configPluralNames.set("DARKOAKFENCEGATE", "DARK OAK FENCE GATES");
        configPluralNames.set("ACACIAFENCEGATE", "ACACIA FENCE GATES");
        configPluralNames.set("SPRUCEFENCE", "SPRUCE FENCES");
        configPluralNames.set("BIRCHFENCE", "BIRCH FENCES");
        configPluralNames.set("JUNGLEFENCE", "JUNGLE FENCES");
        configPluralNames.set("DARKOAKFENCE", "DARK OAK FENCES");
        configPluralNames.set("ACACIAFENCE", "ACACIA FENCES");
        configPluralNames.set("PRISMARINESHARD", "PRISMARINE SHARDS");
        configPluralNames.set("PRISMARINECRYSTAL", "PRISMARINE CRYSTALS");
        configPluralNames.set("RABBITFOOT", "RABBIT FEET");
        configPluralNames.set("RABBITHIDE", "RABBIT HIDES");
        configPluralNames.set("ARMORSTAND", "ARMOR STANDS");
        configPluralNames.set("BANNER", "BANNERS");
        configPluralNames.set("SPRUCEDOOR", "SPRUCE DOORS");
        configPluralNames.set("BIRCHDOOR", "BIRCH DOORS");
        configPluralNames.set("JUNGLEDOOR", "JUNGLE DOORS");
        configPluralNames.set("ACACIADOOR", "ACACIA DOORS");
        configPluralNames.set("DARKOAKDOOR", "DARK OAK DOORS");
        configPluralNames.set("CHORUSFLOWER", "CHORUS FLOWERS");
        configPluralNames.set("CHORUSPLANT", "CHORUS PLANTS");
        configPluralNames.set("ENDGATEWAY", "END GATEWAYS");
        configPluralNames.set("ENDROD", "END RODS");
        configPluralNames.set("ENDSTONEBRICK", "END STONE BRICKS");
        configPluralNames.set("GRASSPATH", "GRASS PATHS");
        configPluralNames.set("PURPURBLOCK", "PURPUR BLOCKS");
        configPluralNames.set("PURPURPILLAR", "PURPUR PILLARS");
        configPluralNames.set("PURPURSTAIR", "PURPUR STAIRS");
        configPluralNames.set("PURPURSLAB", "PURPUR SLABS");
        configPluralNames.set("STRUCTUREBLOCK", "STRUCTURE BLOCKS");
        configPluralNames.set("BEETROOTSEED", "BEETROOT SEEDS");
        configPluralNames.set("ENDCRYSTAL", "END CRYSTALS");
        configPluralNames.set("LINGERINGPOTION", "LINGERING POTIONS");
        configPluralNames.set("SHIELD", "SHIELDS");
        configPluralNames.set("SPECTRALARROW", "SPECTRAL ARROWS");
        configPluralNames.set("TIPPEDARROW", "TIPPED ARROWS");
        configPluralNames.set("MAGMA", "MAGMA BLOCKS");
        configPluralNames.set("NETHERWARTBLOCK", "NETHER WART BLOCKS");
        configPluralNames.set("REDNETHERBRICK", "RED NETHER BRICKS");
        configPluralNames.set("BONEBLOCK", "BONE BLOCKS");
        configPluralNames.set("STRUCTUREBLOCK", "STRUCTURE BLOCKS");
        configPluralNames.set("OBSERVER", "OBSERVERS");
        configPluralNames.set("SHULKERSHELL", "SHULKER SHELLS");
        configPluralNames.set("TOTEMOFUNDYING", "TOTEMS OF UNDYING");
        configPluralNames.set("WHITESHULKERBOX", "WHITE SHULKER BOXES");
        configPluralNames.set("ORANGESHULKERBOX", "ORANGE SHULKER BOXES");
        configPluralNames.set("MAGENTASHULKERBOX", "MAGENTA SHULKER BOXES");
        configPluralNames.set("LIGHTBLUESHULKERBOX", "LIGHT BLUE SHULKER BOXES");
        configPluralNames.set("YELLOWSHULKERBOX", "YELLOW SHULKER BOXES");
        configPluralNames.set("LIMESHULKERBOX", "LIME SHULKER BOXES");
        configPluralNames.set("PINKSHULKERBOX", "PINK SHULKER BOXES");
        configPluralNames.set("GRAYSHULKERBOX", "GRAY SHULKER BOXES");
        configPluralNames.set("LIGHTGRAYSHULKERBOX", "LIGHT GRAY SHULKER BOXES");
        configPluralNames.set("CYANSHULKERBOX", "CYAN SHULKER BOXES");
        configPluralNames.set("PURPLESHULKERBOX", "PURPLE SHULKER BOXES");
        configPluralNames.set("BLUESHULKERBOX", "BLUE SHULKER BOXES");
        configPluralNames.set("BROWNSHULKERBOX", "BROWN SHULKER BOXES");
        configPluralNames.set("GREENSHULKERBOX", "GREEN SHULKER BOXES");
        configPluralNames.set("REDSHULKERBOX", "RED SHULKER BOXES");
        configPluralNames.set("BLACKSHULKERBOX", "BLACK SHULKER BOXES");
        try {
            configPluralNames.save(configFilePluralNames);
        } catch (Exception ignored) {
        }
    }
}